language: ruby
cache: bundler
bundler_args: --without benchmarks console tools
script: "bundle exec rake ci"
after_success:
  - '[ "${TRAVIS_JOB_NUMBER#*.}" = "1" ] && [ "$TRAVIS_BRANCH" = "master" ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - jruby-9.1.9.0
env:
  global:
    - COVERAGE='true'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change
    on_failure: always
    on_start: false
