language: ruby
dist: trusty
sudo: required
cache: bundler
bundler_args: --without sql benchmarks console tools
script: "bundle exec rake ci"
after_success:
  - '[ "${TRAVIS_JOB_NUMBER#*.}" = "1" ] && [ "$TRAVIS_BRANCH" = "master" ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.4.0
  - 2.3
  - 2.2
  - rbx-3
  - jruby
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
    - COVERAGE='true'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change
    on_failure: always
    on_start: false
